### ISSUE TITLE
KeyError: 'airTime'

### ISSUE THREAD

**Issue by rpi3ha** [custom-components/sensor.sonarr_upcoming_media#1]
Hi,

I'm using this and the sensor for radarr as well. Both are placed in the same folder, if that's a problem. Radarrr works fine, but I get this error during the startup of HomeAssistant when the sonarr script is enabled.

Setup details:
Running on Hass.io (Raspberry Pi 3+), HomeAssistant version 0.78.3
Running version '0.0.7' of this script (that's the newest version as far as I can see).

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 243, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/config/custom_components/sensor/sonarr_upcoming_media.py", line 124, in device_state_attributes
    attributes['airtime' + str(attribNum)] = show['series']['airTime']
KeyError: 'airTime'
```

Got any suggestions on what might resolve this?

**Comment by rpi3ha** [comment]
My sensor.yaml-entry looks like this:

```
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: !secret sonarr_port
  days: 14
  ssl: false
```

**Comment by maykar** [comment]
Can you post your sonarr API response for me? 

http://{ your sonarr IP & port }/api/calendar?apikey={ your API key }&start=2018-10-3&end=2018-10-17

**Comment by rpi3ha** [comment]
I think I know might cause it based on the response. Are Norwegian/Danish/Swedish letters supported? Like æøå? One of the shows are the Danish series called "Klovn" and the summary is in Danish. The response is very long, I could send it in pm on discord if you need it to confirm?

**Comment by maykar** [comment]
Just updated to remove airTime attribute as I just realized it's no longer used in the card.  Try the new version.

**Comment by rpi3ha** [comment]
That did the trick, cheers!
