### ISSUE TITLE
Custom element doesn't exist: upcoming-media-card.

### ISSUE THREAD

**Issue by eightsixeight** [custom-components/sensor.sonarr_upcoming_media#10]
**Describe the Bug**
Custom element doesn't exist: upcoming-media-card. 

**The Error**
Custom element doesn't exist: upcoming-media-card.
{
  "type": "custom:upcoming-media-card",
  "entity": "sensor.sonarr_upcoming_media"
}
AND 

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?
YES

**What data does the sensor display if any?**
DISPLAYS THE JSON DATA ON adding a normal sensor widget.

Sonarr_Upcoming_Media
[{"title_default": "$title", "line1_default": "$episode", "line2_default": "$release", "line3_default": "$rating - $runtime", "line4_default": "$number - $studio", "icon": "mdi:arrow-down-bold"}, {"airdate": "2019-08-05T02:00:00Z", "release": "$day, $time", "flag": false, "title": "Preacher", "episode": "Masada", "number": "S04E01", "runtime": 45, "studio": "AMC", "rating": 

**What displays when visiting the API URL from the troubleshooting guide?**
API is working

**Does the default Home Assistant Sonarr component work for you?**
didnt know there was one.

**Home Assistant Version**
What version of HA are you running?
0.96.5
frontend version: 20190721.1 - latest
**Additional Context**

seems all examples refer to lovelave.yaml vs raw editor in newest versions..

all examples show -type js and url whilst the new one seems to be -url and type js 
inversed - part...

manually adding as a manual card 

  Sample for ui-lovelace.yaml:
  - type: custom:upcoming-media-card
    entity: sensor.sonarr_upcoming_media
    title: Upcoming TV

i get 

Custom element doesn't exist: upcoming-media-card.
{
  "type": "custom:upcoming-media-card"
}

**Comment by maykar** [comment]
Somehow I just didn't see this issue, but this is an issue for the card and not the component.

It doesn't matter which goes first, type or js. Errors like this usually happen when the resources section isn't pointing to the file, whether that's because of a typo or using `www` instead of `local`. This can also happen if this is the first time you've used the `www` folder and haven't restarted.
