### ISSUE TITLE
Senors not creating?

### ISSUE THREAD

**Issue by ethanopp** [custom-components/sensor.sonarr_upcoming_media#11]
**Describe the Bug**
Platform error: sensor - Integration 'sonarr_upcoming_media' not found.

**The Error**
Copy and paste the full error from Home Assistant
Platform error: sensor - Integration 'sonarr_upcoming_media' not found.

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?
Yes

**What data does the sensor display if any?**
Feel free to censor information pertaining to titles, networks, etc.
Sensor is not created

**What displays when visiting the API URL from the troubleshooting guide?**
Feel free to censor information pertaining to titles, networks, etc.
accurate json...

**Does the default Home Assistant Sonarr component work for you?**
This is important to know, helps rule out issues with your Sonarr installation.
Yes

**Home Assistant Version**
What version of HA are you running?
Latest (docker)

**Additional Context**

Where exactly are the component files supposed to be placed?
does `/custom_components/sonarr_upcoming_media/` go in `/custom-lovelace`?

The user guide just says copy to this dir, but not necessarily where the dir should be placed. I've tried several base dir's but cant seem to get the sensor to create.

**Comment by maykar** [comment]
If this is your first custom component, create the `custom_component` in your main "config" directory.

**Comment by ethanopp** [comment]
Thanks that did it!
