### ISSUE TITLE
Not getting banner pictures

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-components/sensor.sonarr_upcoming_media#13]
**Describe the Bug**
Im not getting banner pictures:

![image](https://user-images.githubusercontent.com/9917659/70739712-bc5ebc80-1d17-11ea-95bc-c5929a2c3ee1.png)

**The Error**
Tried to serve up '/config/www/community/upcoming-media-card/sonarr_upcoming_media.js' but it does not exist
19:34 custom_components/hacs/http.py (ERROR) - bericht kwam voor het eerst om 19:32 en verschijnt 3 malen
Tried to serve up '/config/www/community/upcoming-media-card/radarr_upcoming_media.js' but it does not exist
19:34 custom_components/hacs/http.py (ERROR) - bericht kwam voor het eerst om 19:32 en verschijnt 3 malen

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?

**What data does the sensor display if any?**
sensor.sonarr_upcoming_media | Online | data: [{"title_default": "$title", "line1_default": "$episode", "line2_default": "$release", "line3_default": "$rating - $runtime", "line4_default": "$number - $studio", "icon": "mdi:arrow-down-bold"}, {"airdate": "2019-12-12T02:00:00Z", "release": "$day, $time", "flag": false, "title": "Vikings", "episode": "Ghosts, Gods and Running Dogs", "number": "S06E03", "runtime": 45, "studio": "History", "rating": "\u2605 8.8", "genres": "Action, Drama", "poster": "https://artworks.thetvdb.com/banners/posters/260449-3_t.jpg", "fanart": "https://artworks.thetvdb.com/banners/fanart/original/260449-19_t.jpg"}, {"airdate": "2019-12-14T01:00:00Z", "release": "$day, $time", "flag": false, "title": "The Blacklist", "episode": "Katarina Rostova", "number": "S07E10", "runtime": 45, "studio": "NBC", "rating": "\u2605 8.7", "genres": "Action, Crime, Drama", "poster": "https://artworks.thetvdb.com/banners/posters/266189-1_t.jpg", "fanart": "https://artworks.thetvdb.com/banners/fanart/original/266189-1_t.jpg"}, {"airdate": "2019-12-19T02:00:00Z", "release": "$day, $time", "flag": false, "title": "Vikings", "episode": "All the Prisoners", "number": "S06E04", "runtime": 45, "studio": "History", "rating": "\u2605 8.8", "genres": "Action, Drama", "poster": "https://artworks.thetvdb.com/banners/posters/260449-3_t.jpg", "fanart": "https://artworks.thetvdb.com/banners/fanart/original/260449-19_t.jpg"}, {"airdate": "2020-01-15T02:00:00Z", "release": "$day, $date $time", "flag": false, "title": "Arrow", "episode": "Crisis on Infinite Earths (4)", "number": "S08E08", "runtime": 45, "studio": "The CW", "rating": "\u2605 8.2", "genres": "Action, Adventure, Crime, Drama, Science Fiction", "poster": "https://artworks.thetvdb.com/banners/posters/257655-19_t.jpg", "fanart": "https://artworks.thetvdb.com/banners/fanart/original/257655-12_t.jpg"}, {"airdate": "2020-01-22T02:00:00Z", "release": "$day, $date $time", "flag": false, "title": "Arrow", "episode": "Green Arrow and the Canaries", "number": "S08E09", "runtime": 45, "studio": "The CW", "rating": "\u2605 8.2", "genres": "Action, Adventure, Crime, D
-- | -- | --

**What displays when visiting the API URL from the troubleshooting guide?**
[
  {
    "seriesId": 30,
    "episodeFileId": 0,
    "seasonNumber": 6,
    "episodeNumber": 3,
    "title": "Ghosts, Gods and Running Dogs",
    "airDate": "2019-12-11",
    "airDateUtc": "2019-12-12T02:00:00Z",
    "overview": "Lagertha is visited by women from nearby villages and they feast together happily, however the community is shattered by shocking events. In Kiev, Oleg continues to be friendly to Ivar who is aware of the threat he poses not only to himself, but also to the young heir of the throne. Bjorn has answered the call and comes to the aid of an old enemy, but all is not right as disaster looms for his forces.",
    "hasFile": false,
    "monitored": true,
    "absoluteEpisodeNumber": 72,
    "unverifiedSceneNumbering": false,
    "series": {
      "title": "Vikings",
      "sortTitle": "vikings",
      "seasonCount": 6,
      "status": "continuing",
      "overview": "Vikings follows the adventures of Ragnar Lothbrok the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods, legend has it that he was a direct descendant of Odin, the god of war and warriors.",
      "network": "History",
      "airTime": "21:00",
      "images": [
        {
          "coverType": "fanart",
          "url": "https://artworks.thetvdb.com/banners/fanart/original/260449-19.jpg"
        },
        {
          "coverType": "banner",
          "url": "https://artworks.thetvdb.com/banners/graphical/260449-g3.jpg"
        },
        {
          "coverType": "poster",
          "url": "https://artworks.thetvdb.com/banners/posters/260449-3.jpg"
        }
      ],
      "seasons": [
        {
          "seasonNumber": 0,
          "monitored": false
        },
        {
          "seasonNumber": 1,
          "monitored": false
        },
        {
          "seasonNumber": 2,
          "monitored": false
        },
        {
          "seasonNumber": 3,
          "monitored": false
        },
        {
          "seasonNumber": 4,
          "monitored": false
        },
        {
          "seasonNumber": 5,
          "monitored": true
        },
        {
          "seasonNumber": 6,
          "monitored": true
        }
      ],
      "year": 2013,
      "path": "/volume1/library/TV Shows/Vikings",
      "profileId": 1,
      "seasonFolder": true,
      "monitored": true,
      "useSceneNumbering": false,
      "runtime": 45,
      "tvdbId": 260449,
      "tvRageId": 31136,
      "tvMazeId": 29,
      "firstAired": "2013-03-03T00:00:00Z",
      "lastInfoSync": "2019-12-12T10:39:20.746104Z",
      "seriesType": "standard",
      "cleanTitle": "vikings",
      "imdbId": "tt2306299",
      "titleSlug": "vikings",
      "certification": "TV-MA",
      "genres": [
        "Action",
        "Drama"
      ],
      "tags": [],
      "added": "2019-06-09T11:15:48.376003Z",
      "ratings": {
        "votes": 11561,
        "value": 8.8
      },
      "qualityProfileId": 1,
      "id": 30
    },
    "id": 2576
  }
]

**Does the default Home Assistant Sonarr component work for you?**
Yes

**Home Assistant Version**
latest of today:  0.103.0

**Additional Context**
Few moths earlier it worked, i mover over to hacs, logs says it cannot find those files, cause there not there, check it, there not there. Cant find any download link to the radarr_upcoming_media.js not sure if we need this still, after hacs got intergrated, willing to help me? Thanks! Radarr has the same error but this works while file does not excist.

**Comment by maykar** [comment]
It looks like you've got a few issues here. One, turn off your add blocker. Two, where are you referring to radarr_upcoming_media.js? That file has never existed. The only javascript files that you should be using is the upcoming media card one.

**Comment by maykar** [comment]
Same with `sonarr_upcoming_media.js` these files don't exist.

I imagine you've added them to your resources maybe, but you should remove them.

**Comment by IIIdefconIII** [comment]
Thanks the addblocker was indeed the trick, ugh should have find that myself, anyway:

![image](https://user-images.githubusercontent.com/9917659/70773703-72f28980-1d78-11ea-8df7-be37f042c3a7.png)


in HACS:
![image](https://user-images.githubusercontent.com/9917659/70773727-830a6900-1d78-11ea-8a79-2de01b771e37.png)

The text below says: 
When installed, it will be in '/ config / custom_components / sonarr_upcoming_media', you still have to add it to your 'configuration.yaml' file.

So that confused me.
