### ISSUE TITLE
Sonarr via SSL "cannot be reached"

### ISSUE THREAD

**Issue by fasm** [custom-components/sensor.sonarr_upcoming_media#15]
**Describe the Bug**
I have setup all of the appropriate plugins/integrations and have thus far been able to connect Plex via SSL. When I test Sonarr without SSL it works just fine, but when I enable SSL, it says it cannot be reached. 

**The Error**
 [custom_components.sonarr_upcoming_media.sensor] Host X.X.X.X is not available

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Yes

**What displays when visiting the API URL from the troubleshooting guide?**
Accessing the API via the URL with SSL works, yes. 

**Does the default Home Assistant Sonarr component work for you?**
It works just fine, as long as SSL is not used to connect.

**Home Assistant Version**
What version of HA are you running?
Home Assistant 0.108.6

And yes, I did change ssl to true and the port was changed to the corresponding SSL port.

**Comment by ludeeus** [comment]
> [custom_components.sonarr_upcoming_media.sensor] Host X.X.X.X is not available

This indicates that you are using HTTPS with an IP, that does not work since the certificate would not be able to validate.
Use non-SSL or the hostname that the certificate is registered to.
