### ISSUE TITLE
Images don't render

### ISSUE THREAD

**Issue by mew0717** [custom-components/sensor.sonarr_upcoming_media#16]
**Describe the Bug**

Love the card, and all the info is there as expected except for imagery.  I've tried it with and without the image_style tag, but to no avail.

`entity: sensor.sonarr_upcoming_media
title: Upcoming TV Shows
type: 'custom:upcoming-media-card'
image_style: poster
`
https://www.dropbox.com/s/iip71u4x6ta16p6/Screenshot%202020-05-30%2010.57.50.png?dl=0
Running: Home Assistant 0.110.2

**Comment by maykar** [comment]
Try whitelisting HA in your ad blocker

**Comment by mew0717** [comment]
That solved it!  You da man!
