### ISSUE TITLE
Addblocker blocks images from thetvdb

### ISSUE THREAD

**Issue by bobvmierlo** [custom-components/sensor.sonarr_upcoming_media#19]
**Small improvement suggestion:**
When using an addon like 'Addblocker' on a desktop browser this blocks all the images (posters and fanart) which are retrieved from thetvdb. Took me some time to figure this out, might wanna add this as an important note to your README.md

**Comment by maykar** [comment]
It's the first thing listed in the [troubleshooting guide](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md).
