### ISSUE TITLE
Sensor will not create

### ISSUE THREAD

**Issue by crider17** [custom-components/sensor.sonarr_upcoming_media#20]
Hello - Please let me know if this is not the right place for this. I'm newish to HA and this is my first custom component. Following the instructions:
1. I created a \www\custom_components\sonarr_upcoming_media folder and copied the 3 files to it. 
2. I took the steps to install the card. Creating a \www\custom-lovelace\upcoming-media-card folder and copying upcoming-media-card.js to it.
3. Here is my configuration.yaml
- platform: sonarr_upcoming_media
    api_key: **correct API**
    host: **correct IP**
    port: 8989
    days: 7
    ssl: false
    max: 10
4. I do not have a ui-lovelace.yaml so I have the following in my raw configuration editor:
- badges: []
    cards:
      - type: 'custom:upcoming-media-card'
        entity: sensor.sonarr_upcoming_media
        title: Upcoming TV
    title: Media
    path: media
5. I also have the following under Lovelace Dashboards > Resources:
URL: local\custom-lovelace\upcoming-media-card\upcoming-media-card.js
Resource Type: JavaScript Module

When I rebooted I do see an "Upcoming TV" card in my Media tab, however - no data.
When I run "Check Configuration" under Server Controls I get:
Platform error sensor.sonarr_upcoming_media - Integration 'sonarr_upcoming_media' not found.
When I look under Developer Tools, States, I do not see a sensor.sonarr_upcoming_media entity.

I'm sure I'm just missing something silly but I've spent a considerable amount of time tinkering with it with no solution. Can you spot my problem?

Thanks!

**Comment by maykar** [comment]
The custom_components folder doesn't reside in /www/ it is inside your main config folder

**Comment by crider17** [comment]
Thank you for your fast reply!

I made the suggested change. I now have: config\custom_components\sonarr_upcoming_media folder with 

- _init_.py
- manifest.json
- sensor.py

files in the folder.

Unfortunately nothing has changed. I still have no sensor. 

There is one odd result of the change though, when I run "Check Configuration" under Server Controls I get nothing. Just an endless spinning circle. When I back out the change (remove the custom_components folder) and restart I am again able to run a "Check Configuration" resulting in the error that I previously mentioned "Platform error sensor.sonarr_upcoming_media - Integration 'sonarr_upcoming_media' not found"

Any idea what is causing this problem? 

Thanks again for your help.

**Comment by maykar** [comment]
Sounds like either you need to restart after installing the component in the correct place or there is an error in your configuration.yaml somewhere, but it's too little information for me to guess what the issue might be.

**Comment by crider17** [comment]
It appears that this is tied directly to this custom component. If I have the custom_components folder as you suggested, and the configuration.yaml code of:
- platform: sonarr_upcoming_media
    api_key: **correct API**
    host: **correct IP**
    port: 8989
    days: 7
    ssl: false
    max: 10
in place - I get the endless spinning circle when trying to check the config.

If I comment out the configuration.yaml code above but leave the custom_components folder in place I can run a check config with no errors.

If I remove the custom_components folder, but leave the configuration.yaml code in place I can run a check config with previous error, but it runs.

Only when I have both the custom_components folder in place AND the configuration.yaml code in place am I unable to run a check config process. 

And...at no time do I ever see a sensor getting created.

I restart the host always between each step. Probably overkill but I just want to make sure the system cycles. 

Does that information help? What do you suggest my next steps would be?

Thanks!

**Comment by maykar** [comment]
Just in case you haven't already or if you didn't copy from the raw files on github. Download the zip from releases:

**Comment by crider17** [comment]
That was it! I replaced the files from the zip and I've got a sensor and and data now. 

I appreciate your quick help!
