### ISSUE TITLE
Please add Exclusions

### ISSUE THREAD

**Issue by Mermyx** [custom-components/sensor.sonarr_upcoming_media#22]
a feature to be able to exclude certain shows from being pick up would be very useful

Example:
exclude_keywords:
      - name of show

**Comment by mkanet** [comment]
Hi @Mermyx please forgive the extremely late response.  **Would you still like to see this?**  I could add support for this on Upcoming Media Card.

**Comment by mkanet** [comment]
Im going to close this issue for now.
