### ISSUE TITLE
Would sonarr being behind NGINX Proxy Manager stop this working?

### ISSUE THREAD

**Issue by 1liminal1** [custom-components/sensor.sonarr_upcoming_media#31]
**Describe the Bug**
Hey mate, 

This is more a quick question then me expecting you to fix anything. This isn't working for me, but I suspect it being behind NGINX Proxy manager being the culprit. Im just wanting to know what you think? And if you do think it could be that, any directions I could look in? 

Thank you :)

**The Error**
Copy and paste the full error from Home Assistant

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?

**What data does the sensor display if any?**
Feel free to censor information pertaining to titles, networks, etc.

**What displays when visiting the API URL from the troubleshooting guide?**
Feel free to censor information pertaining to titles, networks, etc.

**Does the default Home Assistant Sonarr component work for you?**
This is important to know, helps rule out issues with your Sonarr installation.

**Home Assistant Version**
What version of HA are you running?

**Additional Context**

**Comment by mkanet** [comment]
I have Sonarr behind an NGINX reverse proxy too.  I don't think that will work.  I have it set like below to prevent unnecessary issues.

```yaml
  - platform: sonarr_upcoming_media
    api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    host: 192.168.1.2
    port: 8129
    days: 5
    max: 10
```

**Comment by 1liminal1** [comment]
Ahh ok, annoying. 

I have all that hidden in the underlying docker network. The only thing exposed is the proxy server. 

I wonder if there is some config to pass it though correctly. 

Anyway, I appreciate the response, thank you :)
