### ISSUE TITLE
Connection not working though Reverse Proxy, can we set the API URL?

### ISSUE THREAD

**Issue by 1liminal1** [custom-components/sensor.sonarr_upcoming_media#32]
**Describe the Bug**
Trying to use the sonarr_upcoming_media component gives the error sonarr.domain.com cannot be reached
**The Error**
 sonarr.domain.com cannot be reached

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
https://domian.com/sonarr/api/calendar?apikey=xxxxxxxxxxxxxx&start=2029-01-31&end=2024-02-28

I'm not sure what the path for the API is but can you tell me if this should work, or I can change the URL for the integration? 

**What data does the sensor display if any?**
Feel free to censor information pertaining to titles, networks, etc.

**What displays when visiting the API URL from the troubleshooting guide?**
Feel free to censor information pertaining to titles, networks, etc.

**Does the default Home Assistant Sonarr component work for you?**
This is important to know, helps rule out issues with your Sonarr installation.

**Home Assistant Version**
2024.2.4

**Additional Context**

**Comment by mkanet** [comment]
Hi @1liminal1, you should be specifying an IP address, not domain name.  If you try to do this behind a reverse proxy, it changes the way the data is presented.  I also have a reverse proxy.  I might look into this later to see if I can add support for this; but no promises.  

For example:
`configuration.yaml`
```yaml
  - platform: sonarr_upcoming_media
    api_key: 285e2aba1c05234fdc2a1
    host: 192.168.1.2
    port: 8181
    days: 5
    max: 10
```

**Comment by 1liminal1** [comment]
OK, so you're not using SSL at all? If there was someone listening on the network they could get your API key :(

**Comment by mkanet** [comment]
@1liminal1 These integrations weren't made by me.  I inherited these integrations (and Upcoming Media Card) just recently only to prevent them from completely dying since the original author completely stopped supporting them over 2 years ago.

**Having said that, adding SSL support support should be relatively simple; just a few lines of code changes.**  I will most likely add this a little later down the road to all these integrations.

**Comment by maykar** [comment]
Original author here, though it's been a while since I've looked at this, I can tell you that SSL worked without issue before. To troubleshoot this issue in the past you would use the URL from the troubleshooting doc to connect directly to the API and if there is no response that means the issue doesn't lie with the component, but elsewhere

**Comment by maykar** [comment]
Try adding `v3` to the URL like so in a browser and see if you get a reply:

`https://domian.com/sonarr/api/v3/calendar?apikey=xxxxxxxxxxxxxx&start=2029-01-31&end=2024-02-28`

**Comment by mkanet** [comment]
> Original author here, though it's been a while since I've looked at this, I can tell you that SSL worked without issue before. To troubleshoot this issue in the past you would use the URL from the troubleshooting doc to connect directly to the API and if there is no response that means the issue doesn't lie with the component, but elsewhere. As long as that URL hasn't changed, it's a good indicator of where to start troubleshooting.

Hi @maykar!  Thanks for confirming.  I haven't made any significant changes yet that would affect the original intended functionality.  Ill have to assume it still works like it did before.  

@1liminal1 is your configuration setup like below (using a numeric IP address instead of domain name`)?
```yaml
sensor:
  - platform: sonarr_upcoming_media
    api_key: XXXXXXXXXXXXXXX
    host: 192.168.1.2
    port: 8080
    ssl: true
    verify_ssl: true #optional
``

If it still doesnt work

**Comment by 1liminal1** [comment]
Hey guys, 

First of all, just to be clear, I'm not complaining LOL. This was all done to help yourselfs, and you could have kept that way, but you published to the community, so thank you both :) 

I just want it to be secure :) 

I  exposed the default Sonarr port (and Radarr) on the container with http so it all does work, just not with SSL

So with the v3 path I get the JSON (I'm assuming that's what it is?) in Sonarr (not Radarr, though maybe out of scope here) 

```
sensor:
  - platform: sonarr_upcoming_media
    api_key: XXXXXXXXXXXXXXX
    host: sonarr.domain.com
    port: 443
    ssl: true
```

Is how I had it set up, just for your info 

Thanks guys :)

**Comment by mkanet** [comment]
@1liminal1 A quick look at the code shows that it does allow support for SSL.  I have my sonarr instance behind an NGINX reverse proxy too.  I can confirm it doesn't work for me either.  It's possible the issue is caused by the reverse proxy is changing how the data is presented/expected.  

Anyway, I'll take a look into this when I get some more time to see what the real cause is; and see if I can find a solution that works.

**Comment by 1liminal1** [comment]
That's what I suspect as well and I have found some references for it 

https://wiki.servarr.com/sonarr/installation/reverse-proxy

I did try adding it to the advanced section of the proxy host, but it didn't make a difference for me. Anyway, let me know if you can get time to figure it out and need me to do any testing :)

Thanks mate!

**Comment by mkanet** [comment]
> That's what I suspect as well and I have found some references for it
> 
> https://wiki.servarr.com/sonarr/installation/reverse-proxy
> 
> I did try adding it to the advanced section of the proxy host, but it didn't make a difference for me. Anyway, let me know if you can get time to figure it out and need me to do any testing :)
> 
> Thanks mate!

You're welcome.  I was right.  The link you provided only accommodates for Sonarr's web interface, **not its API responses**.  We got super lucky, I found a solution on my first Google search result.  It works great.  I will also do this for Radarr as well while I'm at it.

```
# Sonarr Reverse Proxy
# Be sure to set your Base-URL in Sonarr
location /sonarr {
        proxy_pass http://127.0.0.1:8989/sonarr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_no_cache $cookie_session;
        # Allow the Sonarr API through if you enable Auth on the block above
        location /sonarr/api { 
                proxy_pass http://127.0.0.1:8989/sonarr/api;
        }
}
```

https://github.com/Organizr/Config-Collections-for-Nginx/blob/master/Apps/sonarr.conf

Enjoy...

**Comment by 1liminal1** [comment]
Thanks mate, 

Are you adding this to the GUI? 

![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10505942/ccc11bac-c6fb-4f45-8020-a15da36dc732)

**Comment by mkanet** [comment]
I dont use the GUI.  I just edited the files directly.  This is what mine looks like exactly

nginx.conf
```
    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name sonarr.domain.com;
        location / {
            proxy_pass http://localhost:8181;
            include ./conf/proxy.conf;
        }
        location /api {
            proxy_pass http://localhost:8181/api;
            include ./conf/proxy.conf;
        }
    }
```

proxy.conf
port_in_redirect off;
proxy_http_version  1.1;
proxy_cache_bypass                  $http_upgrade;
proxy_set_header Upgrade            $http_upgrade;
proxy_set_header Connection         $connection_upgrade;
proxy_set_header Accept-Encoding    "";
proxy_set_header Host               $host;
proxy_set_header X-Real-IP          $remote_addr;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-Host   $host;
proxy_set_header X-Forwarded-Port   $server_port;
proxy_set_header Sec-Websocket-Extensions $http_sec_websocket_extensions;
proxy_set_header Sec-Websocket-Key $http_sec_websocket_key;
proxy_set_header Sec-Websocket-Protocol $http_sec_websocket_protocol;
proxy_set_header Sec-Websocket-Version $http_sec_websocket_version;
proxy_connect_timeout 300;
proxy_send_timeout 300;
proxy_read_timeout 300;
proxy_buffers 512 512k;
proxy_buffer_size 512k;
proxy_busy_buffers_size 512k;

**Comment by 1liminal1** [comment]
Thanks so much for that, Im using NGINX proxy manager though a container so you cant edit those files, they are not persistent  :(

Anyway, it works, I just need to figure out how it works though the GUI

Thanks mate, I appreciate you helping as much as you have :)

**Comment by mkanet** [comment]
@1liminal1 FYI, the new deep_link feature wasn't working properly when using sonarr_upcoming_media, radarr_upcoming_media, and plex recently added integrations behind a reverse proxy.  I just finished adding full support for them across the board.

**Comment by 1liminal1** [comment]
Thanks for letting me know. I just haven't been able to get Nginx Prox Manager working with the custom locations sadly 

![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10505942/9c47ff70-d6a6-48f8-88b6-a22e40bae8c7)


It just breaks it. 

Not expecting you to help with this BTW HAHA, but if you see that and go... Well its obviously this, then let me know :) lol

Overwise it will have to go on the backlog for now lol 

Thanks again!

**Comment by mkanet** [comment]
Would you believe I never have even used the Nginx Proxy Manager?  Otherwise, I would try to help if I could.  Anyway, good luck.

**Comment by 1liminal1** [comment]
What are you actually using?

**Comment by mkanet** [comment]
I'm kind of a weirdo, I prefer hosting everything on my Windows box without Docker.   I'm using a special Windows version of NGINX:  http://nginx-win.ecsds.eu/.  Its performance is comparable to the official NIX version of NGINX.

**Comment by 1liminal1** [comment]
There are no weirdos, just people doing diff things :) 

And hey! At least yours works HAHA :)

**Comment by 1liminal1** [comment]
Hey, I just finished my Dakboard/ HA set up and thought I would share :) Have MMwave sensors that turn off the screen (Though the Pi running a MQTT script) after 20 mins of inaction. Or when I play something though the Apple TV (though that is a bit hit and miss lol) 

![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10505942/81ecb554-be1a-46a8-9f55-2d6283ebac9a)

This is the HA screen and you can see the upcoming media card front and center.

Appreciate the hard work :)

**Comment by mkanet** [comment]
@1liminal1 Thats cool!  I also have MMwave sensors (Aurora brand); however, I only use them for my bathroom and toilet.

**Comment by 1liminal1** [comment]
I started making them with using https://esphome.io/components/sensor/ld2410.html and esp32 s3 

[HLK-LD2410](https://www.thingiverse.com/thing:5782554)

With this case, they are so cheap and easy, got about 10 of them floating around now :) lol

The whole place is covered, so useful, and not just for lights. Music, fans, turning off the amp and music when I leave my room. Or things like, If I leave my desk and walk to the kitchen, change the music over to that Alexa. But only if occupancy is no longer detected at my desk. SO if the wife walks into the kitchen it wont change. Its not perfect of course, but it works pretty well :)
