### ISSUE TITLE
Linking to Shows doesn't work

### ISSUE THREAD

**Issue by evanrich** [custom-components/sensor.sonarr_upcoming_media#33]
**Describe the Bug**
Clicking on shows takes you to sonarr with a invalid show (show not found)
![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/518320/33a00bb9-c3b2-4a51-99a5-df208c3d40f7)

Some examples (the url the card links to vs the actual url in sonarr):

card: `/series/shōgun`
sonarr: `series/shogun-2024`

card:`/series/ncis:-hawai'i`
Sonarr:`/series/ncis-hawaii`

card: `/series/the-cleaning-lady-(us)`
sonarr: `/series/the-cleaning-lady-us`

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?
Yes

**What displays when visiting the API URL from the troubleshooting guide?**
This isn't an API problem it's something with how the card is formatting the urls. ( looked at the api url examples but they don't apply here)

**Does the default Home Assistant Sonarr component work for you?**
yes although it's not deeplinking back to the show like this is

**Home Assistant Version**
2024.3.3 core

**Additional Context**
Querying sonarr's api directly for the ncis hawaii episode gives me this:

```
{
    "seriesId": 213,
    "tvdbId": 10305828,
    "episodeFileId": 0,
    "seasonNumber": 3,
    "episodeNumber": 6,
    "title": "Operation Red Rabbit",
    "airDate": "2024-04-01",
    "airDateUtc": "2024-04-02T02:00:00Z",
    "runtime": 43,
    "overview": "When the fiancée of a vanished naval officer seeks the help of NCIS, the team reveals his secrets go much deeper than she suspected. Meanwhile, Sam recruits Kai to be his wingman.",
    "hasFile": false,
    "monitored": true,
    "unverifiedSceneNumbering": false,
    "grabbed": false,
    "id": 52560
  }
```

If i then take "213" and use the api to get the series, i get this:
```
{
  "title": "NCIS: Hawai'i",
  "alternateTitles": [
    {
      "title": "NCIS Hawaii",
      "seasonNumber": -1
    },
    {
      "title": "Navy CIS Hawaii",
      "seasonNumber": -1
    }
  ],
  "sortTitle": "ncis hawaii",
  "status": "continuing",
  "ended": false,
.
.
.
```

so it seems that the card is taking the "title" but sonarr is using the "sortTitle"?  For shogun, it's the opposite:

```
{
  "title": "Shōgun",
  "alternateTitles": [
    {
      "title": "Shogun 2024",
      "seasonNumber": -1
    }
  ],
  "sortTitle": "shōgun",
```

the card uses either sortTitle or title, but sonarr is using the "alternate title"?

**Comment by mkanet** [comment]
Hi @evanrich thank you so much for reporting this issue.  I just pushed out the fix for this.  It should work now in all cases.

**Comment by evanrich** [comment]
confirmed working thanks!
