### ISSUE TITLE
URL base missing from deeplink when using SSL and FQDN

### ISSUE THREAD

**Issue by Haknor74** [custom-components/sensor.sonarr_upcoming_media#41]
**Describe the Bug**
When using FQDN and SSL the URL base is missing from deep link

**The Error**
Copy and paste the full error from Home Assistant

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
Well, did you?

**What data does the sensor display if any?**
Feel free to censor information pertaining to titles, networks, etc.

**What displays when visiting the API URL from the troubleshooting guide?**
Feel free to censor information pertaining to titles, networks, etc.

**Does the default Home Assistant Sonarr component work for you?**
This is important to know, helps rule out issues with your Sonarr installation.

**Home Assistant Version**
What version of HA are you running?
2024.5.5

**Additional Context**
![sonarr med ssl](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/17417626/d0a8c65b-b34f-4d5b-9909-6b84e810a15d)
![url with ssl](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/17417626/fd422420-3b12-4135-8185-8619868ef7f5)

**Comment by mkanet** [comment]
Hi @Haknor74 thank you so much for reporting the issue.  I just fixed it in version `0.4.2`.  URL Base is now working correctly.  Please update your Sonarr Integration to the new version.  I will close this issue as soon as you confirm.

I also need to make sure the sibling repo [Radarr Upcoming Media](https://github.com/custom-components/sensor.radarr_upcoming_media) also handles URL Base correctly.

**Comment by Haknor74** [comment]
Hi @mkanet 
Thank you for the quick response. I can confirm issue is resolved i sonarr version 0.4.2 :)

for your informasion:
I just downloaded radarr version 0.4.1, but this versjon still shows as 0.4.0 in HA and issue still persists

**Comment by mkanet** [comment]
Thanks for confirming, you should see the new version for Radarr soon if you're updating VIA HACS. The repo already has the new version.  Maybe you wouldn't mind confirming that the Radarr one also works after you try the update?  If you don't get the update today for the Radarr integration please let me know, if possible.

**Comment by Haknor74** [comment]
Hello, confirming radarr is working.
I had to download the raw files.
Source code (zip) is still old version, updated last week?
<img width="927" alt="screenshoot" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/17417626/d6ed66cd-41f7-4331-8686-dcad704123ee">

**Comment by mkanet** [comment]
Sorry, I finally realized what you were talking about.  I'm glad you told me!  Now it should be.  You can update to version `0.4.2` which is what 0.4.1 was supposed to be.

![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/811008/7f26a7aa-96e3-4554-ae5f-65455925265d)
