### ISSUE TITLE
Refresh of data not occuring

### ISSUE THREAD

**Issue by the-jeffski** [custom-components/sensor.sonarr_upcoming_media#43]
I've started to see the component not refresh data. For example today is the 13th but it shows to me upcoming on the 11th. 

I've realized it seems to do a fetch at the point of any HA restart but then never seems to advance the date selection in the http request so it just shows the same data ongoing. 

Any suggestion of what Lines I could add a debug trace to to see what the request is being made so we can troubleshoot this?

**Comment by mkanet** [comment]
Sonarr hasnt changed its api in a while. I havent made any changes either lately to this integration. I know this doesn't help much, but your ssue is almost certainly specific to your configuration/connectivity. If there was a reproducable issue there would be several people reporting this issue too.

**Comment by the-jeffski** [comment]
Appreciate that - I can see in the sonarr trace log the request is made for the right dates and the sensor shows an updater date but change date is always from restart. Its very weird.

**Comment by the-jeffski** [comment]
OK, so experimenting I have solved it - or at least found the scenario. When setting up the addon I gave the sensor a name during the setup rather than leave the field blank. It seems when named I get a sensor called   sensor.sonarr_sonarr_upcoming_media  which only updates once.  When I ignore the name field so sensor is called  sensor.sonarr_upcoming_media  it updates fine!

**Comment by mkanet** [comment]
Glad you figured it out what was going on!
